############################
## MODULES
## Add more modules if needed
## https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/chrede88/qubt
  - path: github.com/hugomods/gravatar
  - path: github.com/hugomods/google-analytics
